//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Proj.Grupo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoria_Publicacao
    {
        public int id_autor { get; set; }
        public int id_publicacao { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Publicacao Publicacao { get; set; }
    }
}
