//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Proj.Grupo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Docente()
        {
            this.Coordenadors = new HashSet<Coordenador>();
            this.Diretors = new HashSet<Diretor>();
            this.Autoria_Projeto = new HashSet<Autoria_Projeto>();
        }
    
        public int id { get; set; }
        public int id_utilizador { get; set; }
        public string nome { get; set; }
        public Nullable<int> id_departamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coordenador> Coordenadors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diretor> Diretors { get; set; }
        public virtual Autoria_Publicacao Autoria_Publicacao { get; set; }
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autoria_Projeto> Autoria_Projeto { get; set; }
        public virtual Coordenador Coordenador { get; set; }
        public virtual Diretor Diretor { get; set; }
    }
}
