//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Proj.Grupo2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Grupo2_Plataforma_Departamental : DbContext
    {
        public Entities_Grupo2_Plataforma_Departamental()
            : base("name=Entities_Grupo2_Plataforma_Departamental")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coordenador> Coordenadors { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Diretor> Diretors { get; set; }
        public virtual DbSet<Docente> Docentes { get; set; }
        public virtual DbSet<Escola> Escolas { get; set; }
        public virtual DbSet<Instituicao> Instituicaos { get; set; }
        public virtual DbSet<Projeto> Projetoes { get; set; }
        public virtual DbSet<Publicacao> Publicacaos { get; set; }
        public virtual DbSet<Utilizador> Utilizadors { get; set; }
        public virtual DbSet<Autoria_Publicacao> Autoria_Publicacao { get; set; }
        public virtual DbSet<Autoria_Projeto> Autoria_Projeto { get; set; }
    }
}
